# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Single step uild and deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # for Azure login
      contents: read    # for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, pdo_pgsql, bcmath, tokenizer, xml

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
            composer validate --no-check-publish 
            composer install --prefer-dist --no-progress --no-dev --optimize-autoloader

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EB5A3068168E48D69C84B32FD4539E26 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_98DB87DDB7C74B399EA072968F138533 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A4463D7116A54F4894477B5A941F2D6C }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'lloyds-laravel'
          slot-name: 'Production'
          package: .

      - name: Run Laravel migrations and cache
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp ssh --name lloyds-laravel --resource-group WE-Lloyds-Playground --command "php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache"

